name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: "true"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    steps:
      - name: Ensure musl installed
        run: sudo apt-get install -y musl-dev musl-tools musl gcc-aarch64-linux-gnu && rustup target add ${{ matrix.arch }}-unknown-linux-musl

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2

      - name: Run unit tests
        run: cargo test

  build-release-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Ensure musl installed
        run: sudo apt-get install -y musl-dev musl-tools musl && rustup target add ${{ matrix.arch }}-unknown-linux-musl
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Build final release binary
        run: cargo build --release --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
        with:
          name: iam-assumer
          path: target/${{ matrix.arch }}-unknown-linux-musl/release/iam-assumer

  build-release-darwin:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Ensure musl installed
        run: sudo apt-get install -y musl-dev musl-tools musl && rustup target add ${{ matrix.arch }}-apple-darwin
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Build final release binary
        run: cargo build --release --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
        with:
          name: iam-assumer
          path: target/${{ matrix.arch }}-apple-darwin/release/iam-assumer 
      
